const SCHEMA_SEGUIMIENTO = {
  'TTO TXS DEPRESIVO': {
    titulo: 'SEGUIMIENTO DE TRATAMIENTO AMBULATORIO DE PERSONAS CON DEPRESIÓN. (5005190)',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE', actividad:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE (5005190)', subproducto:'TRATAMIENTO AMBULATORIO DE PERSONAS CON DEPRESION (5005190)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaMedica',col:20,sesiones:3,label:'CONSULTA MÉDICA (99215 - 30 A 20 MIN)'},
      {key:'psicoeducacion',col:23,sesiones:1,label:'PSICOEDUCACIÓN AL USUARIO (99207.04 - 45 MIN)'},
      {key:'intervencionIndividual',col:24,sesiones:6,label:'INTERVENCIÓN INDIVIDUAL / PSICOTERAPIA (99207.01 / 90806)'},
    ],
    colsMeta: [{key:'condicion',col:30,label:'CONDICIÓN'},{key:'proyeccion',col:31,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:32,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:33,label:'OBSERVACIÓN'}],
  },
  'TTO VIF. Y SEXUAL > 18 AÑOS': {
    titulo: 'SEGUIMIENTO DE TRATAMIENTO EN VIOLENCIA FAMILIAR (5005189)',
    headerInfo: { producto:'POBLACION CON PROBLEMAS PSICOSOCIALES QUE RECIBEN ATENCION OPORTUNA Y DE CALIDAD', actividad:'TRATAMIENTO DE PERSONAS CON PROBLEMAS PSICOSOCIALES (5005189)', subproducto:'TRATAMIENTO EN VIOLENCIA FAMILIAR EN EL PRIMER NIVEL DE ATENCION NO ESPECIALIZADO (5005189)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'apoderado',col:14,label:'APODERADO O FAMILIAR'},
      {key:'celular',col:15,label:'CELULAR'},{key:'sectorista',col:16,label:'SECTORISTA'},{key:'tamizaje',col:17,label:'TAMIZAJE'},
      {key:'diagnostico',col:18,label:'DIAGNÓSTICO (CIE-10)'},{key:'tipoViolencia',col:19,label:'TIPO DE VIOLENCIA'},
    ],
    gruposSesiones: [
      {key:'fichaRiesgo',col:20,sesiones:1,label:'APLICACIÓN FICHA VALORACIÓN RIESGOS (99207.06)'},
      {key:'consultaSaludMental',col:23,sesiones:2,label:'CONSULTA SALUD MENTAL (99207 - 45 MIN)'},
      {key:'psicoterapiaIndividual',col:25,sesiones:6,label:'PSICOTERAPIA INDIVIDUAL (90806 - 60 MIN)'},
      {key:'intervencionFamiliar',col:31,sesiones:1,label:'INTERVENCIÓN FAMILIAR (C2111.01)'},
      {key:'visitaDomiciliaria',col:32,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:33,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:34,label:'CONDICIÓN'},{key:'proyeccion',col:35,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:36,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:37,label:'OBSERVACIÓN'}],
  },
  'TTO VIOL. INFANTIL  0-17 AÑOS': {
    titulo: 'SEGUIMIENTO TRATAMIENTO NIÑOS/AS AFECTADOS POR MALTRATO INFANTIL',
    headerInfo: { producto:'POBLACION CON PROBLEMAS PSICOSOCIALES QUE RECIBEN ATENCION OPORTUNA Y DE CALIDAD', actividad:'TRATAMIENTO DE PERSONAS CON PROBLEMAS PSICOSOCIALES (5005189)', subproducto:'TRATAMIENTO DE NINOS, NINAS Y ADOLESCENTES AFECTADOS POR MALTRATO INFANTIL (0060614)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'fichaRiesgo',col:20,sesiones:1,label:'APLICACIÓN FICHA VALORACIÓN RIESGOS (99207.06)'},
      {key:'consultaSaludMental',col:23,sesiones:2,label:'CONSULTA SALUD MENTAL (99207 - 45 MIN)'},
      {key:'intervencionIndividual',col:25,sesiones:6,label:'INTERVENCIÓN INDIVIDUAL / PSICOTERAPIA (99207.01 / 90806)'},
      {key:'intervencionFamiliar',col:31,sesiones:3,label:'INTERVENCIÓN FAMILIAR (C2111.01)'},
      {key:'visitaDomiciliaria',col:34,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:35,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:36,label:'CONDICIÓN'},{key:'fur',col:37,label:'FUR'},{key:'fpp',col:38,label:'FPP'},{key:'proyeccion',col:39,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:40,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:41,label:'OBSERVACIÓN'}],
  },
  'TTO V. SEXUAL DE  0-17 AÑOS': {
    titulo: 'SEGUIMIENTO TRATAMIENTO NIÑOS/AS AFECTADOS POR VIOLENCIA SEXUAL',
    headerInfo: { producto:'POBLACION CON PROBLEMAS PSICOSOCIALES QUE RECIBEN ATENCION OPORTUNA Y DE CALIDAD', actividad:'TRATAMIENTO DE PERSONAS CON PROBLEMAS PSICOSOCIALES (5005189)', subproducto:'TRATAMIENTO ESPECIALIZADO DE PERSONAS AFECTADAS POR VIOLENCIA SEXUAL (0060613)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'fichaRiesgo',col:20,sesiones:1,label:'APLICACIÓN FICHA VALORACIÓN RIESGOS (99207.06)'},
      {key:'consultaSaludMental',col:23,sesiones:2,label:'CONSULTA SALUD MENTAL (99207 - 45 MIN)'},
      {key:'intervencionIndividual',col:25,sesiones:6,label:'INTERVENCIÓN INDIVIDUAL / PSICOTERAPIA (99207.01 / 90806)'},
      {key:'intervencionFamiliar',col:31,sesiones:3,label:'INTERVENCIÓN FAMILIAR (C2111.01)'},
      {key:'visitaDomiciliaria',col:34,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:35,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:36,label:'CONDICIÓN'},{key:'proyeccion',col:37,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:38,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:39,label:'OBSERVACIÓN'}],
  },
  'TTO AUTISMO': {
    titulo: 'SEGUIMIENTO TRATAMIENTO AMBULATORIO PERSONAS CON AUTISMO',
    headerInfo: { producto:'POBLACION CON PROBLEMAS PSICOSOCIALES QUE RECIBEN ATENCION OPORTUNA Y DE CALIDAD', actividad:'TRATAMIENTO AMBULATORIO DE NINOS Y NINAS DE 0 A 17 ANOS CON TRASTORNOS MENTALES (5006281)', subproducto:'TRATAMIENTO AMBULATORIO DE NINOS Y NINAS DE 0 A 17 ANOS CON TRASTORNOS DEL ESPECTRO AUTISTA (0070616)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaMedica',col:20,sesiones:2,label:'CONSULTA MÉDICA ESPECIALIZADA (99215 - 45 MIN)'},
      {key:'psicoterapia',col:22,sesiones:6,label:'PSICOTERAPIA INDIVIDUAL (90806 - 60 MIN)'},
      {key:'intervencionGrupal',col:28,sesiones:6,label:'INTERVENCIÓN GRUPAL SALUD MENTAL (99207.02)'},
      {key:'visitaDomiciliaria',col:34,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:35,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:36,label:'CONDICIÓN'},{key:'proyeccion',col:37,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:38,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:39,label:'OBSERVACIÓN'}],
  },
  'TTO TX MENTAL Y COMP. 0-17 AÑOS': {
    titulo: 'SEGUIMIENTO TRATAMIENTO TRASTORNO MENTAL Y COMPORTAMIENTO 0-17 AÑOS',
    headerInfo: { producto:'POBLACION CON PROBLEMAS PSICOSOCIALES QUE RECIBEN ATENCION OPORTUNA Y DE CALIDAD', actividad:'TRATAMIENTO AMBULATORIO DE NINOS Y NINAS DE 0 A 17 ANOS CON TRASTORNOS MENTALES (5006281)', subproducto:'TRATAMIENTO AMBULATORIO DE NINOS Y NINAS DE 0 A 17 ANOS CON TRASTORNOS MENTALES Y/O PROBLEMAS PSICOSOCIALES (5005927)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaSaludMental',col:20,sesiones:2,label:'CONSULTA SALUD MENTAL (99207 - 45 MIN)'},
      {key:'intervencionIndividual',col:22,sesiones:6,label:'INTERVENCIÓN INDIVIDUAL / PSICOTERAPIA (99207.01 / 90806)'},
      {key:'intervencionFamiliar',col:28,sesiones:3,label:'INTERVENCIÓN FAMILIAR (C2111.01)'},
      {key:'visitaDomiciliaria',col:31,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
    ],
    colsMeta: [{key:'condicion',col:32,label:'CONDICIÓN'},{key:'proyeccion',col:33,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:34,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:35,label:'OBSERVACIÓN'}],
  },
  'TTO TXT CX SUICIDA': {
    titulo: 'SEGUIMIENTO TRATAMIENTO CONDUCTA SUICIDA',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE', actividad:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE (5005190)', subproducto:'TRATAMIENTO AMBULATORIO DE PERSONAS CON CONDUCTA SUICIDA (0070610)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaMedica',col:20,sesiones:2,label:'CONSULTA MÉDICA (99215 - 30 MIN)'},
      {key:'psicoeducacion',col:22,sesiones:1,label:'PSICOEDUCACIÓN (99207.04 - 45 MIN)'},
      {key:'psicoterapiaIndividual',col:23,sesiones:6,label:'PSICOTERAPIA INDIVIDUAL (90806 - 60 MIN)'},
      {key:'intervencionFamiliar',col:29,sesiones:2,label:'INTERVENCIÓN FAMILIAR (C2111.01)'},
      {key:'visitaDomiciliaria',col:31,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:32,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:33,label:'CONDICIÓN'},{key:'proyeccion',col:34,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:35,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:36,label:'OBSERVACIÓN'}],
  },
  'TTO TXT ANSIEDAD': {
    titulo: 'SEGUIMIENTO TRATAMIENTO TRASTORNO DE ANSIEDAD',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE', actividad:'PERSONAS CON TRASTORNOS AFECTIVOS Y DE ANSIEDAD TRATADAS OPORTUNAMENTE (5005190)', subproducto:'TRATAMIENTO AMBULATORIO DE PERSONAS CON ANSIEDAD (0070611)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaMedica',col:20,sesiones:2,label:'CONSULTA MÉDICA (99215 - 45 MIN)'},
      {key:'psicoeducacion',col:22,sesiones:1,label:'PSICOEDUCACIÓN (99207.04 - 45 MIN)'},
      {key:'psicoterapiaIndividual',col:23,sesiones:6,label:'PSICOTERAPIA INDIVIDUAL (90806 - 60 MIN)'},
    ],
    colsMeta: [{key:'condicion',col:29,label:'CONDICIÓN'},{key:'proyeccion',col:30,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:31,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:32,label:'OBSERVACIÓN'}],
  },
  'TTO INTERV CONSUMO OH': {
    titulo: 'SEGUIMIENTO INTERVENCIÓN CONSUMO DE ALCOHOL',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDO AL CONSUMO DEL ALCOHOL TRATADAS OPORTUNAMENTE', actividad:'PERSONAS CON TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDO AL CONSUMO DEL ALCOHOL TRATADAS OPORTUNAMENTE (5006282)', subproducto:'INTERVENCIONES BREVES MOTIVACIONALES PARA PERSONAS CON CONSUMO PERJUDICIAL DEL ALCOHOL Y TABACO (5005192)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consejeria',col:20,sesiones:1,label:'CONSEJERÍA ESTILOS VIDA SALUDABLE (99401.13)'},
      {key:'intervencionBreve',col:21,sesiones:6,label:'INTERVENCIÓN BREVE (99207.01 - 30 MIN)'},
    ],
    colsMeta: [{key:'condicion',col:27,label:'CONDICIÓN'},{key:'proyeccion',col:28,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:29,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:30,label:'OBSERVACIÓN'}],
  },
  'TTO DEPENDENCIA OH': {
    titulo: 'SEGUIMIENTO TRATAMIENTO DEPENDENCIA AL ALCOHOL',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDO AL CONSUMO DEL ALCOHOL TRATADAS OPORTUNAMENTE', actividad:'PERSONAS CON TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDO AL CONSUMO DEL ALCOHOL TRATADAS OPORTUNAMENTE (5006282)', subproducto:'INTERVENCION PARA PERSONAS CON DEPENDENCIA DEL ALCOHOL Y TABACO (0070617)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultasMedicas',col:19,sesiones:4,label:'CONSULTAS MÉDICAS (99215 - 30 MIN)'},
      {key:'entrevistaMotivacional',col:23,sesiones:2,label:'ENTREVISTAS MOTIVACIONALES (96150 - 30 MIN)'},
      {key:'psicoterapiaIndividual',col:25,sesiones:4,label:'PSICOTERAPIAS INDIVIDUALES (90806 - 60 MIN)'},
      {key:'intervencionFamiliar',col:29,sesiones:2,label:'INTERVENCIONES FAMILIARES (96100.01 - 60 MIN)'},
      {key:'visitasFamiliares',col:31,sesiones:2,label:'VISITAS FAMILIARES (C0011 - 45 MIN)'},
    ],
    colsMeta: [{key:'condicion',col:33,label:'CONDICIÓN'},{key:'proyeccion',col:34,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:35,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:36,label:'OBSERVACIÓN'}],
  },
  'TTO ESPECT.ESQUIZOFRENIA EE.SS': {
    titulo: 'SEGUIMIENTO TRATAMIENTO ESPECTRO DE ESQUIZOFRENIA',
    headerInfo: { producto:'PERSONAS CON TRASTORNOS MENTALES Y SINDROMES PSICOTICOS TRATADAS OPORTUNAMENTE (3000702)', actividad:'PERSONAS CON TRASTORNOS MENTALES Y DEL COMPORTAMIENTO CON SINDROME PSICOTICO O TRASTORNO ESPECTRO ESQUIZOFRENIA TRATADAS OPORTUNAMENTE', subproducto:'TRATAMIENTO AMBULATORIO A PERSONAS CON SINDROME PSICOTICO O TRASTORNO DEL ESPECTRO DE LA ESQUIZOFRENIA (5005195)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'institucion',col:14,label:'INSTITUCIÓN EDUCATIVA'},
      {key:'apoderado',col:15,label:'APODERADO O FAMILIAR'},{key:'celular',col:16,label:'CELULAR'},{key:'sectorista',col:17,label:'SECTORISTA'},
      {key:'tamizaje',col:18,label:'TAMIZAJE'},{key:'diagnostico',col:19,label:'DIAGNÓSTICO (CIE-10)'},
    ],
    gruposSesiones: [
      {key:'consultaMedica',col:20,sesiones:4,label:'CONSULTA MÉDICA AMBULATORIA (99215 - 45 MIN)'},
      {key:'intervencionIndividual',col:24,sesiones:6,label:'INTERVENCIÓN INDIVIDUAL / PSICOTERAPIA (99207.01 / 90806)'},
      {key:'psicoeducacion',col:30,sesiones:4,label:'PSICOEDUCACIÓN (99207.04 - 30 MIN)'},
      {key:'visitaDomiciliaria',col:34,sesiones:1,label:'VISITA DOMICILIARIA (C0011)'},
      {key:'movilizacionRedes',col:35,sesiones:1,label:'MOVILIZACIÓN REDES DE APOYO (C1043)'},
    ],
    colsMeta: [{key:'condicion',col:36,label:'CONDICIÓN'},{key:'proyeccion',col:37,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:38,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:39,label:'OBSERVACIÓN'}],
  },
  'VIPOL 1 FORTALECIMIENTO': {
    titulo: 'SEGUIMIENTO VIPOL 1 - FORTALECIMIENTO DE REDES DE APOYO',
    headerInfo: { producto:'COMUNIDADES CON POBLACIONES VICTIMAS DE VIOLENCIA POLITICA ATENDIDAS', actividad:'INTERVENCION COMUNITARIA PARA LA RECUPERACION EMOCIONAL DE POBLACIONES VICTIMAS DE VIOLENCIA POLITICA', subproducto:'FORTALECIMIENTO DE REDES DE APOYO PSICOSOCIAL (5005199)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'apoderado',col:14,label:'APODERADO O FAMILIAR'},
      {key:'celular',col:15,label:'CELULAR'},{key:'tamizaje',col:16,label:'TAMIZAJE'},{key:'diagnostico',col:17,label:'DIAGNÓSTICO (Z654)'},
    ],
    gruposSesiones: [{key:'fortalecimientoRedes',col:18,sesiones:6,label:'FORTALECIMIENTO REDES DE APOYO (C0071 + Z654)'}],
    colsMeta: [{key:'condicion',col:24,label:'CONDICIÓN'},{key:'proyeccion',col:25,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:26,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:27,label:'OBSERVACIÓN'}],
  },
  'VIPOL 2 ACOMPAÑAMIENTO': {
    titulo: 'SEGUIMIENTO VIPOL 2 - ACOMPAÑAMIENTO PSICOSOCIAL',
    headerInfo: { producto:'COMUNIDADES CON POBLACIONES VICTIMAS DE VIOLENCIA POLITICA ATENDIDAS', actividad:'INTERVENCION COMUNITARIA PARA LA RECUPERACION EMOCIONAL DE POBLACIONES VICTIMAS DE VIOLENCIA POLITICA', subproducto:'ACOMPANAMIENTO PSICOSOCIAL A VICTIMAS DE VIOLENCIA POLITICA (0070625)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'apoderado',col:14,label:'APODERADO O FAMILIAR'},
      {key:'celular',col:15,label:'CELULAR'},{key:'tamizaje',col:16,label:'TAMIZAJE'},{key:'diagnostico',col:17,label:'DIAGNÓSTICO (Z654)'},
    ],
    gruposSesiones: [{key:'acompañamiento',col:18,sesiones:6,label:'ACOMPAÑAMIENTO PSICOSOCIAL (99207.07 + Z654)'}],
    colsMeta: [{key:'condicion',col:24,label:'CONDICIÓN'},{key:'proyeccion',col:25,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:26,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:27,label:'OBSERVACIÓN'}],
  },
  'VIPOL 3 RECONSTRUCCION': {
    titulo: 'SEGUIMIENTO VIPOL 3 - RECONSTRUCCIÓN DE IDENTIDAD COLECTIVA',
    headerInfo: { producto:'COMUNIDADES CON POBLACIONES VICTIMAS DE VIOLENCIA POLITICA ATENDIDAS', actividad:'INTERVENCION COMUNITARIA PARA LA RECUPERACION EMOCIONAL DE POBLACIONES VICTIMAS DE VIOLENCIA POLITICA', subproducto:'RECONSTRUCCION DE LA IDENTIDAD COLECTIVA (0070626)' },
    colsFijas: [
      {key:'producto',col:0,label:'PRODUCTO'},{key:'actividad',col:1,label:'ACTIVIDAD OPERATIVA'},{key:'subproducto',col:2,label:'SUBPRODUCTO'},
      {key:'numero',col:3,label:'N°'},{key:'psicologo',col:4,label:'NOMBRE DEL PSICÓLOGO(A)'},{key:'fechaAtencion',col:5,label:'FECHA DE ATENCIÓN'},
      {key:'nombres',col:6,label:'APELLIDOS Y NOMBRES'},{key:'edad',col:7,label:'EDAD'},{key:'sexo',col:8,label:'SEXO'},
      {key:'fechaNac',col:9,label:'FECHA DE NACIMIENTO'},{key:'dni',col:10,label:'DNI'},{key:'hcl',col:11,label:'HISTORIA CLÍNICA'},
      {key:'sector',col:12,label:'SECTOR'},{key:'direccion',col:13,label:'DIRECCIÓN'},{key:'apoderado',col:14,label:'APODERADO O FAMILIAR'},
      {key:'celular',col:15,label:'CELULAR'},{key:'tamizaje',col:16,label:'TAMIZAJE'},{key:'diagnostico',col:17,label:'DIAGNÓSTICO (Z654)'},
    ],
    gruposSesiones: [{key:'reconstruccion',col:18,sesiones:6,label:'RECONSTRUCCIÓN IDENTIDAD COLECTIVA (C0006 + Z654)'}],
    colsMeta: [{key:'condicion',col:24,label:'CONDICIÓN'},{key:'proyeccion',col:25,label:'PROYECCIÓN MES A DAR TA'},{key:'referido',col:26,label:'REFERIDO LUGAR Y FECHA'},{key:'observacion',col:27,label:'OBSERVACIÓN'}],
  },
  'CEM PACHITEA': {
    titulo: 'CASOS DEL CENTRO DE EMERGENCIA MUJER - PACHITEA',
    headerInfo: { producto:'CENTRO DE EMERGENCIA MUJER - PACHITEA', actividad:'TERAPIA PSICOLOGICA', subproducto:'ATENCION Y SEGUIMIENTO DE CASOS CEM' },
    dataStart: 2,
    colsFijas: [
      {key:'oficio',col:0,label:'OFICIO'},{key:'fechaRecepcion',col:1,label:'FECHA DE RECEPCION'},
      {key:'asunto',col:2,label:'ASUNTO'},{key:'nombres',col:3,label:'USUARIA'},
      {key:'dni',col:4,label:'DNI'},{key:'edad',col:5,label:'EDAD'},
      {key:'comentario',col:6,label:'COMENTARIO ADICIONAL'},{key:'nivelRiesgo',col:7,label:'NIVEL DE RIESGO'},
      {key:'domicilio',col:8,label:'DOMICILIO'},{key:'celular',col:9,label:'CELULAR'},
      {key:'fechaAtencion',col:10,label:'FECHA DE ATENCION EN CEM'},{key:'deriva',col:11,label:'DERIVA'},
      {key:'observacion',col:12,label:'OBSERVACION'},
    ],
    gruposSesiones: [],
    colsMeta: [],
  },
};

module.exports = SCHEMA_SEGUIMIENTO;
